services:
  - type: web
    name: sug-election-admin
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn admin_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
